version: '2'

services:
  flight-search:
    image: 'docker-flight-search:latest'
    build:
      context: .
    container_name: flight-search
    depends_on:
      - flight-search-db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flight-search-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  flight-search-db:
    image: 'postgres:13.1-alpine'
    container_name: flight-search-db
    ports:
      - 6543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres