package com.demo.flightsearch.api.validators;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import javax.validation.Constraint;
import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;
import javax.validation.Payload;

/**
 * The interface Auto generated value. Used for custom validation
 */
@Target({ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER, ElementType.TYPE_USE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Constraint(
        validatedBy = {AutoGeneratedValue.Validator.class}
)
public @interface AutoGeneratedValue {
    /**
     * Message string.
     *
     * @return the string
     */
    String message() default "'${validatedValue}' cannot be set, it si autogenerated.";

    /**
     * Groups class [ ].
     *
     * @return the class [ ]
     */
    Class<?>[] groups() default {};

    /**
     * Payload class [ ].
     *
     * @return the class [ ]
     */
    Class<? extends Payload>[] payload() default {};

    /**
     * The type Validator.
     */
    public static class Validator implements ConstraintValidator<AutoGeneratedValue, Object> {
        /**
         * Instantiates a new Validator.
         */
        public Validator() {
        }

        public void initialize(AutoGeneratedValue parameters) {
        }

        public boolean isValid(Object value, ConstraintValidatorContext constraintValidatorContext) {
            return value == null;
        }
    }
}