package com.demo.flightsearch.api.searchflight;

import com.demo.flightsearch.api.route.RouteDto;
import com.demo.flightsearch.api.validators.AutoGeneratedValue;
import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.List;
import java.util.UUID;

/**
 * The type Search flight dto.
 */
public class SearchFlightDto {

    @AutoGeneratedValue
    private UUID uuid;

    //@JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
    private List<RouteDto> itinerary;

    private Double totalCostInEuro;

    /**
     * Gets uuid.
     *
     * @return the uuid
     */
    public UUID getUuid() {
        return uuid;
    }

    /**
     * Sets uuid.
     *
     * @param uuid the uuid
     * @return the uuid
     */
    public SearchFlightDto setUuid(UUID uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Gets itinerary.
     *
     * @return the itinerary
     */
    public List<RouteDto> getItinerary() {
        return itinerary;
    }

    /**
     * Sets itinerary.
     *
     * @param itinerary the itinerary
     * @return the itinerary
     */
    public SearchFlightDto setItinerary(List<RouteDto> itinerary) {
        this.itinerary = itinerary;
        return this;
    }

    /**
     * Gets total cost in euro.
     *
     * @return the total cost in euro
     */
    public Double getTotalCostInEuro() {
        return totalCostInEuro;
    }

    /**
     * Sets total cost in euro.
     *
     * @param totalCostInEuro the total cost in euro
     * @return the total cost in euro
     */
    public SearchFlightDto setTotalCostInEuro(Double totalCostInEuro) {
        this.totalCostInEuro = totalCostInEuro;
        return this;
    }

    @Override
    public String toString() {
        return "SearchFlightDto{uuid=" + uuid
                + ", itinerary=" + itinerary
                + ", totalCostInEuro=" + totalCostInEuro
                + "}";
    }
}
